# reverse proxy pra api
server {      
    # escuta na porta 80 (HTTP)                             
    listen 80;
    server_name your-domain.com;
    
    # qualquer rota que chegar
    location / {
        proxy_pass http://api:5000; # encaminha pro service api na porta 5000 (DNS interno do Docker Compose)
        proxy_set_header Host $host; # repassa o hostname original da requisição                                                                    
        proxy_set_header X-Real-IP $remote_addr; # repassa o IP real do cliente (senão a api vê o IP do nginx)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # cadeia de proxies pelo caminho                                    
        proxy_set_header X-Forwarded-Proto $scheme; # protocolo original (http/https)                     
    }                                                                                                   
  } 